<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="base_length" value="0.65"/>
    <xacro:property name="base_width" value="0.5"/>
    <xacro:property name="base_height" value="0.025"/>
    <xacro:property name="base_distance" value="0.20"/>
    <xacro:property name="wheel_radius" value="0.125"/>
    <xacro:property name="wheel_length" value="0.075"/>
    <xacro:property name="hex_crew_radius" value="0.01"/>
    <xacro:property name="hex_crew_height" value="0.175"/>

    <xacro:macro name="hex_crew_link" params="prefix">
        <link name="${prefix}_hex_crew_link">
            <visual>
                <geometry>
                    <cylinder radius="${hex_crew_radius}" length="${base_distance}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="yellow" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${hex_crew_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:cylinder_inertia mass="0.05" radius="${hex_crew_radius}" height="${base_distance}" o_xyz="0 0 0" o_rpy="0 0 0" />
        </link>
    </xacro:macro>

    <xacro:hex_crew_link prefix="first"/>
    <xacro:hex_crew_link prefix="second"/>
    <xacro:hex_crew_link prefix="third"/>
    <xacro:hex_crew_link prefix="fourth"/> 

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="black" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:cylinder_inertia mass="0.25" radius="${wheel_radius}" height="${wheel_length}" o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right"/>
    <xacro:wheel_link prefix="left"/>

    <xacro:macro name="castor_wheel_link" params="prefix">
        <link name="${prefix}_castor_wheel_link">
            <visual>
                <geometry>
                    <sphere radius="${wheel_radius / 2}" />
                </geometry>
            <material name="yellow" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius / 2}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:sphere_inertia mass="0.25" radius="${wheel_radius / 2.0}" o_xyz="0 0 0" o_rpy="0 0 0" />    
        </link>
    </xacro:macro>

    <xacro:castor_wheel_link prefix="first"/>

    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="white" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia mass="0.5" x="${base_length}" y="${base_width}" z="${base_height}" o_xyz="0 0 ${base_height / 2.0}" o_rpy="0 0 0" />  
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>
    
    <link name="second_base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="white" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia mass="0.5" x="${base_length}" y="${base_width}" z="${base_height}"
                           o_xyz="0 0 ${base_height / 2.0}" o_rpy="0 0 0" />  
    </link>

    <joint name="second_base_joint" type="fixed">
        <parent link="base_link" />
        <child link="second_base_link" />
        <origin xyz="0 0 ${base_distance}" rpy="0 0 0" />
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="-${base_width / 2.5} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="-${base_width / 2.5} -${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_castor_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="first_castor_wheel_link" />
        <origin xyz="${base_width / 2} 0 -${wheel_radius / 2}" rpy="0 0 0" />
    </joint> 

    <joint name="first_hex_crew_joint" type="fixed">
        <parent link="base_link" />
        <child link="first_hex_crew_link" />
        <origin xyz="-${base_width / 2.5} -${base_width / 2.5} ${base_distance / 2.0}" rpy="0 0 0" />
    </joint> 

    <joint name="second_hex_crew_joint" type="fixed">
        <parent link="base_link" />
        <child link="second_hex_crew_link" />
        <origin xyz="${base_width / 2.5} ${base_width / 2.5} ${base_distance / 2.0}" rpy="0 0 0" />
    </joint> 

    <joint name="third_hex_crew_joint" type="fixed">
        <parent link="base_link" />
        <child link="third_hex_crew_link" />
        <origin xyz="${base_width / 2.5} -${base_width / 2.5} ${base_distance / 2.0}" rpy="0 0 0" />
    </joint> 

    <joint name="fourth_hex_crew_joint" type="fixed">
        <parent link="base_link" />
        <child link="fourth_hex_crew_link" />
        <origin xyz="-${base_width / 2.5} ${base_width / 2.5} ${base_distance / 2.0}" rpy="0 0 0" />
    </joint> 

</robot>


