<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="camera_length" value="0.05"/>
    <xacro:property name="camera_width" value="0.1"/>
    <xacro:property name="camera_height" value="0.05"/>
    <xacro:property name="imu_length" value="0.075"/>
    <xacro:property name="imu_width" value="0.025"/>
    <xacro:property name="imu_height" value="0.02"/>   
    <xacro:property name="lidar_radius" value="0.08"/>
    <xacro:property name="lidar_height" value="0.05"/>

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia mass="0.15" x="${camera_length}" y="${camera_width}" z="${camera_height}" o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <link name = "camera_link_optical"/>

    <link name = "imu_link">
        <visual>
            <geometry>
                <box size="${imu_length} ${imu_width} ${imu_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${imu_length} ${imu_width} ${imu_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia mass="0.1" x="${imu_length}" y="${imu_width}" z="${imu_height}" o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <joint name = "base_camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="${(base_length + camera_length) / 2} 0 ${base_height + camera_height / 2}" rpy="0 0 0"/>
    </joint>

    <gazebo reference="camera_link">
        <sensor name="camera" type="camera">
            <camera>
                <horizontal_fov>1.0472</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>15</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
                <optical_frame_id>camera_link_optical</optical_frame_id>
                <camera_info_topic>camera/camera_info</camera_info_topic>
            </camera>
            <always_on>true</always_on>
            <update_rate>20</update_rate>
            <visualize>true</visualize>
            <topic>camera/image_raw</topic>
        </sensor>
    </gazebo>

    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
        <origin xyz="0 0 0" rpy="-${pi/2} 0 -${pi/2}"/>
    </joint>
    
    <joint name = "base_imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0 0 ${base_height + imu_height / 2.0}" rpy="0 0 0"/>
    </joint>

</robot>